<?php

use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        $langs = [
            ['code' => 'af', 'title' => '', 'eng_title' => 'Afrikaans', 'image' => ''],
            ['code' => 'sq', 'title' => '', 'eng_title' => 'Albanian', 'image' => ''],
            ['code' => 'am', 'title' => '', 'eng_title' => 'Amharic', 'image' => ''],
            ['code' => 'ar', 'title' => '', 'eng_title' => 'Arabic', 'image' => ''],
            ['code' => 'hy', 'title' => '', 'eng_title' => 'Armenian', 'image' => ''],
            ['code' => 'az', 'title' => '', 'eng_title' => 'Azerbaijani', 'image' => ''],
            ['code' => 'eu', 'title' => '', 'eng_title' => 'Basque', 'image' => ''],
            ['code' => 'be', 'title' => '', 'eng_title' => 'Belarusian', 'image' => ''],
            ['code' => 'bn', 'title' => '', 'eng_title' => 'Bengali', 'image' => ''],
            ['code' => 'bs', 'title' => '', 'eng_title' => 'Bosnian', 'image' => ''],
            ['code' => 'bg', 'title' => '', 'eng_title' => 'Bulgarian', 'image' => ''],
            ['code' => 'ca', 'title' => '', 'eng_title' => 'Catalan', 'image' => ''],
            ['code' => 'ceb', 'title' => '', 'eng_title' => 'Cebuano', 'image' => ''],
            ['code' => 'zh-CN', 'title' => '', 'eng_title' => 'Chinese (Simplified)', 'image' => ''],
            ['code' => 'zh-TW', 'title' => '', 'eng_title' => 'Chinese (Traditional)', 'image' => ''],
            ['code' => 'co', 'title' => '', 'eng_title' => 'Corsican', 'image' => ''],
            ['code' => 'hr', 'title' => '', 'eng_title' => 'Croatian', 'image' => ''],
            ['code' => 'cs', 'title' => '', 'eng_title' => 'Czech', 'image' => ''],
            ['code' => 'da', 'title' => '', 'eng_title' => 'Danish', 'image' => ''],
            ['code' => 'nl', 'title' => '', 'eng_title' => 'Dutch', 'image' => ''],
            ['code' => 'en', 'title' => '', 'eng_title' => 'English', 'image' => ''],
            ['code' => 'eo', 'title' => '', 'eng_title' => 'Esperanto', 'image' => ''],
            ['code' => 'et', 'title' => '', 'eng_title' => 'Estonian', 'image' => ''],
            ['code' => 'fi', 'title' => '', 'eng_title' => 'Finnish', 'image' => ''],
            ['code' => 'fr', 'title' => '', 'eng_title' => 'French', 'image' => ''],
            ['code' => 'fy', 'title' => '', 'eng_title' => 'Frisian', 'image' => ''],
            ['code' => 'gl', 'title' => '', 'eng_title' => 'Galician', 'image' => ''],
            ['code' => 'ka', 'title' => '', 'eng_title' => 'Georgian', 'image' => ''],
            ['code' => 'de', 'title' => '', 'eng_title' => 'German', 'image' => ''],
            ['code' => 'el', 'title' => '', 'eng_title' => 'Greek', 'image' => ''],
            ['code' => 'gu', 'title' => '', 'eng_title' => 'Gujarati', 'image' => ''],
            ['code' => 'ht', 'title' => '', 'eng_title' => 'Haitian Creole', 'image' => ''],
            ['code' => 'ha', 'title' => '', 'eng_title' => 'Hausa', 'image' => ''],
            ['code' => 'haw', 'title' => '', 'eng_title' => 'Hawaiian', 'image' => ''],
            ['code' => 'iw', 'title' => '', 'eng_title' => 'Hebrew', 'image' => ''],
            ['code' => 'hi', 'title' => '', 'eng_title' => 'Hindi', 'image' => ''],
            ['code' => 'hmn', 'title' => '', 'eng_title' => 'Hmong', 'image' => ''],
            ['code' => 'hu', 'title' => '', 'eng_title' => 'Hungarian', 'image' => ''],
            ['code' => 'is', 'title' => '', 'eng_title' => 'Icelandic', 'image' => ''],
            ['code' => 'ig', 'title' => '', 'eng_title' => 'Igbo', 'image' => ''],
            ['code' => 'id', 'title' => '', 'eng_title' => 'Indonesian', 'image' => ''],
            ['code' => 'ga', 'title' => '', 'eng_title' => 'Irish', 'image' => ''],
            ['code' => 'it', 'title' => '', 'eng_title' => 'Italian', 'image' => ''],
            ['code' => 'ja', 'title' => '', 'eng_title' => 'Japanese', 'image' => ''],
            ['code' => 'jw', 'title' => '', 'eng_title' => 'Javanese', 'image' => ''],
            ['code' => 'kn', 'title' => '', 'eng_title' => 'Kannada', 'image' => ''],
            ['code' => 'kk', 'title' => '', 'eng_title' => 'Kazakh', 'image' => ''],
            ['code' => 'km', 'title' => '', 'eng_title' => 'Khmer', 'image' => ''],
            ['code' => 'ko', 'title' => '', 'eng_title' => 'Korean', 'image' => ''],
            ['code' => 'ku', 'title' => '', 'eng_title' => 'Kurdish', 'image' => ''],
            ['code' => 'ky', 'title' => '', 'eng_title' => 'Kyrgyz', 'image' => ''],
            ['code' => 'lo', 'title' => '', 'eng_title' => 'Lao', 'image' => ''],
            ['code' => 'la', 'title' => '', 'eng_title' => 'Latin', 'image' => ''],
            ['code' => 'lv', 'title' => '', 'eng_title' => 'Latvian', 'image' => ''],
            ['code' => 'lt', 'title' => '', 'eng_title' => 'Lithuanian', 'image' => ''],
            ['code' => 'lb', 'title' => '', 'eng_title' => 'Luxembourgish', 'image' => ''],
            ['code' => 'mk', 'title' => '', 'eng_title' => 'Macedonian', 'image' => ''],
            ['code' => 'mg', 'title' => '', 'eng_title' => 'Malagasy', 'image' => ''],
            ['code' => 'ms', 'title' => '', 'eng_title' => 'Malay', 'image' => ''],
            ['code' => 'ml', 'title' => '', 'eng_title' => 'Malayalam', 'image' => ''],
            ['code' => 'mt', 'title' => '', 'eng_title' => 'Maltese', 'image' => ''],
            ['code' => 'mi', 'title' => '', 'eng_title' => 'Maori', 'image' => ''],
            ['code' => 'mr', 'title' => '', 'eng_title' => 'Marathi', 'image' => ''],
            ['code' => 'mn', 'title' => '', 'eng_title' => 'Mongolian', 'image' => ''],
            ['code' => 'my', 'title' => '', 'eng_title' => 'Myanmar (Burmese)', 'image' => ''],
            ['code' => 'ne', 'title' => '', 'eng_title' => 'Nepali', 'image' => ''],
            ['code' => 'no', 'title' => '', 'eng_title' => 'Norwegian', 'image' => ''],
            ['code' => 'ny', 'title' => '', 'eng_title' => 'Chichewa (Nyanja)', 'image' => ''],
            ['code' => 'ps', 'title' => '', 'eng_title' => 'Pashto', 'image' => ''],
            ['code' => 'fa', 'title' => '', 'eng_title' => 'Persian', 'image' => ''],
            ['code' => 'pl', 'title' => '', 'eng_title' => 'Polish', 'image' => ''],
            ['code' => 'pt', 'title' => '', 'eng_title' => 'Portuguese', 'image' => ''],
            ['code' => 'pa', 'title' => '', 'eng_title' => 'Punjabi', 'image' => ''],
            ['code' => 'ro', 'title' => '', 'eng_title' => 'Romanian', 'image' => ''],
            ['code' => 'ru', 'title' => '', 'eng_title' => 'Russian', 'image' => ''],
            ['code' => 'sm', 'title' => '', 'eng_title' => 'Samoan', 'image' => ''],
            ['code' => 'gd', 'title' => '', 'eng_title' => 'Scots Gaelic', 'image' => ''],
            ['code' => 'sr', 'title' => '', 'eng_title' => 'Serbian', 'image' => ''],
            ['code' => 'st', 'title' => '', 'eng_title' => 'Sesotho', 'image' => ''],
            ['code' => 'sn', 'title' => '', 'eng_title' => 'Shona', 'image' => ''],
            ['code' => 'sd', 'title' => '', 'eng_title' => 'Sindhi', 'image' => ''],
            ['code' => 'si', 'title' => '', 'eng_title' => 'Sinhala', 'image' => ''],
            ['code' => 'sk', 'title' => '', 'eng_title' => 'Slovak', 'image' => ''],
            ['code' => 'sl', 'title' => '', 'eng_title' => 'Slovenian', 'image' => ''],
            ['code' => 'so', 'title' => '', 'eng_title' => 'Somali', 'image' => ''],
            ['code' => 'es', 'title' => '', 'eng_title' => 'Spanish', 'image' => ''],
            ['code' => 'su', 'title' => '', 'eng_title' => 'Sundanese', 'image' => ''],
            ['code' => 'sw', 'title' => '', 'eng_title' => 'Swahili', 'image' => ''],
            ['code' => 'sv', 'title' => '', 'eng_title' => 'Swedish', 'image' => ''],
            ['code' => 'tl', 'title' => '', 'eng_title' => 'Filipino (Tagalog)', 'image' => ''],
            ['code' => 'tg', 'title' => '', 'eng_title' => 'Tajik', 'image' => ''],
            ['code' => 'ta', 'title' => '', 'eng_title' => 'Tamil', 'image' => ''],
            ['code' => 'te', 'title' => '', 'eng_title' => 'Telugu', 'image' => ''],
            ['code' => 'th', 'title' => '', 'eng_title' => 'Thai', 'image' => ''],
            ['code' => 'tr', 'title' => '', 'eng_title' => 'Turkish', 'image' => ''],
            ['code' => 'uk', 'title' => '', 'eng_title' => 'Ukrainian', 'image' => ''],
            ['code' => 'ur', 'title' => '', 'eng_title' => 'Urdu', 'image' => ''],
            ['code' => 'uz', 'title' => '', 'eng_title' => 'Uzbek', 'image' => ''],
            ['code' => 'vi', 'title' => '', 'eng_title' => 'Vietnamese', 'image' => ''],
            ['code' => 'cy', 'title' => '', 'eng_title' => 'Welsh', 'image' => ''],
            ['code' => 'xh', 'title' => '', 'eng_title' => 'Xhosa', 'image' => ''],
            ['code' => 'yi', 'title' => '', 'eng_title' => 'Yiddish', 'image' => ''],
            ['code' => 'yo', 'title' => '', 'eng_title' => 'Yoruba', 'image' => ''],
            ['code' => 'zu', 'title' => '', 'eng_title' => 'Zulu', 'image' => '']
        ];

        foreach ($langs as $lang) {
            \App\Models\Main\Language::create([
                'code' => $lang['code'],
                'title' => $lang['title'],
                'eng_title' => $lang['eng_title'],
                'image' => $lang['image']
            ]);
        }
    }
}
